// Shared source for the changelog surfaces.
//
// The Home page shows a short preview (the newest few, `summary` only) and the main menu's
// Update Log screen shows the full list with every `details` bullet — both read from here,
// so a release is described in one place instead of being copy-pasted into the Home island.
// (The Guide tab keeps its own FAQ-style "Update Log" section.) Newest first.
//
// UPDATES[0] is also the version the main menu prints on its Update Log link, so the top
// entry and the two "Public Build" badges in App.svelte / MainMenu.svelte move together.

export const UPDATES = [
    {
        ver: 'Beta 1.7.3',
        title: 'Ultimate Career — Big Games, Languages & Morale With Teeth',
        summary: 'The week before a final now feels like one, your first Worlds is marked as the moment it is, and the circuit is six regions in four languages you have to actually learn. Solo queue can grind you down, losing hurts, and second and third signature champions finally work.',
        details: [
            'NEW — Events before the big ones. The week a playoff, First Stand, MSI or Worlds tie lands, the hours around it now come with something: the bus, the booth, the noise through the wall, a message from home, the opposing mid laner in a corridor. Fourteen of them, and the biggest stages read differently from a routine playoff week. They arrive before you press Play, so what they do to your form and your head is carried into the game rather than announced after it.',
            'NEW — Your first time at each tournament is marked. Reaching a playoff, First Stand, MSI or Worlds for the first time in a career opens a moment written for it, once, and never again. You will have spent real years getting to the last one.',
            'EXPANDED — 26 new life events, taking the pool from 46 to 72. New material on the room, the contract, the press, the patch and the body, plus a whole new strand about moving countries and what it costs you.',
            'FIXED — a week could only ever show you one event. Anything else it produced was thrown away before it reached the screen. Every event a week generates now actually arrives, and a week can occasionally hand you two.',
            'NEW — Languages. Six regions speak four languages, and you start fluent in the one you grew up with. Korea works in Korean, China in Mandarin, Brazil in Portuguese, and Europe, North America and the Asia-Pacific all work in English. That asymmetry is the point: a European can take an LCS offer with nothing to learn, a Korean has to study English to move west at all, and nobody who is not Korean signs in the LCK without Korean.',
            'NEW — Language Lessons, a weekly activity. Roughly six sessions gets you past the bar a foreign club will sign you at, fourteen makes you fluent. You learn faster young and faster with Game Knowledge, and the gains slow as you approach the top. You pick what you are studying on the Transfers screen.',
            'NEW — Living somewhere teaches it to you. Play a season abroad and the language comes in on its own, slowly, whether you study or not — and you arrive with a crash course already done. Sign in Korea at 19 and you will not still be lost at 24.',
            'CHANGED — clubs abroad want you more as you learn. A foreign side used to be flatly less interested in you, full stop. That penalty now shrinks as you learn their language, down to roughly a third of what it was at fluency, and they call you more often too. Learning Korean is the difference between the LCK being a wall and the LCK being an option.',
            'CLEARER — an offer from abroad tells you the truth. The relocation line used to say "new language, new solo queue, no friends" while no language existed anywhere in the game. It now names the language, your level in it, and what you would still need. A club that will not sign you says which language it works in and how far off you are.',
            'NEW — Solo queue can grind you down. Queueing once in a week is free. Queue again and again inside the same week and it starts costing you health, more each time, and a losing session on top of that puts you on tilt in a way one bad night never did. Sessions where you actually win still lift you a little. It is a grind you can choose; it is no longer a grind with no downside.',
            'CHANGED — losing hurts, and so does a bad game. A defeat already cost you morale; a run of them now costs more each time, and a game where you fed rather than merely lost costs more again. Both are deliberately capped and both only ever subtract — a good KDA is already paid for in your match rating, and paying for it twice would have quietly inflated every score in the mode.',
            'FIXED (critical) — second and third signature champions. Buying the Second Signature and Third Signature perks gave you a slot that nothing in the game could fill: the ability existed, the draft was ready to use it, and there was simply no screen anywhere that let you designate one, so 740 legacy points bought nothing at all. This was listed as fixed in Beta 1.7.0 and was not — the fix stopped one layer short of the screen. Your Profile now shows your signature slots, what is in them, and lets you add and drop extra picks for the same cost as re-maining. Your main is untouched when you add one.',
            'NOTE — existing careers are safe. A save made before this update starts fluent in your home language and in the language of the club you are already at, so nobody wakes up unable to renew a contract or unable to justify the team they have played three seasons for. Nothing about your career is reset or re-rolled.',
            'BALANCE — measured, not guessed. Across a full run of simulated twelve-year careers: every career learns a second language, every one of them moves abroad at least once, and match ratings are unchanged against the ceiling the mode is held to. Morale now has real downward pressure for the first time — it had almost none before, and fifteen things pushing it up.',
        ],
    },
    {
        ver: 'Beta 1.7.2',
        title: 'Seasons Stay With The Club You Played Them For',
        summary: 'Transferring used to hand your season to your new club: the record was wiped to 0-0, the placement came from a league you had not played in, and your trophies were re-credited to a team you had never played a game for.',
        details: [
            'FIXED (critical) — a season is now filed under the club you actually played it for. The transfer window opens before the summer split is written into your history, so signing elsewhere in the offseason handed the whole season to your new club — which had played none of it. Your record showed 0-0 under their name.',
            'FIXED — the same thing happened in spring, and worse, because academies will call you mid-season. A move any time between your last league game and the split being written down wiped the record of a season you had already played.',
            'FIXED — honours now stay with the club you won them at. A regional title or a domestic double won with one team was being re-credited to whichever team you had just signed for, so your trophy cabinet named the wrong club and your old team showed nothing for a season they won.',
            'FIXED — the league placement on a finished season is read from the table you actually played in, rather than from your new club\'s division.',
            'NOTE — promotion is not a transfer. Being promoted from an academy to the main team still files that split under the academy, because that is where you played it. Your history reads as the two separate seasons it was.',
        ],
    },
    {
        ver: 'Beta 1.7.1',
        title: 'Combo Drill Fixed & Clubs That Set Their Own Standards',
        summary: 'The new Mechanics drill was genuinely unplayable — the approach rings never moved and the targets never appeared. That is fixed, the circles are much smaller and the ring closes far more slowly. Academies and amateur sides now each set their own signing bar instead of every club in a tier wanting the same thing.',
        details: [
            'FIXED (critical) — the Combo Execution drill did not work. The approach ring was drawn once when a target spawned and then never redrawn, so it never actually closed, and because a target fades in from nothing on the frame it is born, every circle rendered fully transparent and stayed that way. There was nothing on screen to time against. It now animates properly: the ring shrinks onto the circle and you hit it as they meet, which is what the drill was always meant to be.',
            'FIXED — the drill was calling you early when you were on time. Your press was scored against the last drawn frame rather than the actual moment you clicked, and because that reading is always a fraction behind, every hit was judged as up to a sixteenth of a second earlier than it really was — consistently, in the same direction, on a window a twentieth of a second wide. Timing is read straight off the clock now, so a press on the beat is scored as a press on the beat.',
            'FIXED — the ring was thinnest at the exact moment you needed to read it. Scaling a circle scales its outline too, so the ring was drawn thick and obvious while it was still far away and faded to a hairline as it closed. It now holds its weight all the way in and firms up into the beat, and the target itself lights up for the final stretch.',
            'CHANGED — the circles are much smaller. They were sized at nearly a third of the field across, with the ring opening at three times that, so two overlapping targets covered most of the board. They are now about a fifth of that area.',
            'CHANGED — the drill is a lot slower. The ring takes 1.85 seconds to close on Basic instead of 1.2, and the gap between targets went from 0.95s to 1.55s, so a new player gets a proper look at the cue before it matters. Advanced and Elite were slowed by the same proportion, and the run-in before the first target is longer.',
            'BALANCE — the timing windows were re-derived after the slowdown. A session that would have been worth an average result before is still worth exactly an average result now, at all three difficulties, so nothing about the change quietly made Mechanics cheaper to train than every other attribute.',
            'CHANGED — amateur (tier 3) sides will now sign much weaker players. They are the weakest organised teams in the game and were asking for a higher rating than some academies, which made no sense: the open circuit was gatekeeping harder than the league above it. They now look at players from around 40 rated and Gold, rather than 48 and Emerald.',
            'CHANGED — academies (tier 2) now want a minimum of 60 rated and Platinum before they will talk to you. That is a real step up from the old bar, and it makes the amateur circuit the genuine first rung rather than something you skip past.',
            'NEW — every club sets its own standard. A tier used to be a single number: every academy in the world wanted exactly the same rating and the same rank. Now the bar climbs with the club\'s own strength, so BLG Junior asks for 69 while INTZ Academy asks for 62, and two clubs of equal strength still differ slightly. Standards also shift between seasons, so a club that passed on you last winter may not next time.',
            'CLEARER — a club that will not sign you now says so in its own name and quotes its own numbers ("BLG Junior are looking at 69 rated players. You are 60"), instead of a single generic line that was the same for every club in the tier.',
        ],
    },
    {
        ver: 'Beta 1.7.0',
        title: 'Ultimate Career — The Season Overhaul',
        summary: 'The biggest Ultimate Career update yet: a league table that is finally a real competition, tournaments that last as long as their window, First Stand, fearless draft, Bo3 regular seasons, a burnout system, contract terminations, a brand-new Mechanics minigame, and a career path that starts where a real one does.',
        details: [
            'FIXED (critical) — the league table was fiction. Every club except yours had its games invented on the spot each week, with fresh random pairings, one club sitting out whenever the pool was odd, and the simulation running in all 40 weeks of the year while fixtures only existed in 18. Your own results were never added to your opponents\' records, and your row counted playoff, MSI and Worlds games while everybody else\'s counted league games only. Measured: a player winning 70% of their games reached playoff seeding on 18 games against AI sides who had played 23–26, seeded 7th, and missed the cut. There is now ONE real fixture list per division per split — every club plays the same games, in the same weeks, and the table is stable across page loads. Regional titles rose 63→76 and Split MVP awards 12→65 purely because you are no longer structurally disadvantaged.',
            'FIXED (critical) — simulated matches skipped champion select entirely. Roughly half the games in a career are simmed rather than played by hand, and in every one of them the draft never happened: your matchup and champion proficiency were not scored, and no proficiency was banked. Half of every career was quietly bypassing three systems. Simmed games now draft properly.',
            'NEW — Fearless draft. In a Bo3 or Bo5, a champion you lock in is off the board for the rest of the series. You cannot ride one pick through a whole playoff tie any more, which is exactly the point: your second and third champions have to be real. A series that goes the distance can spend four of them.',
            'NEW — Best-of-three regular seasons, decided by region. Korea, China and the Asia-Pacific play Bo3 every week; Europe, North America and Brazil play Bo1. A series is still one row in the table however many games it took, and the amateur circuit stays Bo1 because it is scrims. Picking a region now changes what your weeks actually look like.',
            'FIXED — tournaments no longer happen all at once. Playoffs, MSI and Worlds each own a multi-week window, and the whole bracket used to resolve on the day it opened: reaching a final meant playing a quarter-final, a semi-final and a final — fifteen games of Bo5 — inside a single week, with the following two weeks completely empty. Rounds are now spread across the window with the final on its last week. Worlds is a proper four-week run: sixteen teams, one round a week.',
            'NEW — First Stand. A sixth event, played across weeks 2–4, contested by one club per region — the reigning champions and nobody else. You qualify by winning your summer title, and you play it the following February, so the berth carries across the year the way a real one does. It is deliberately worth less than MSI: six champions in February is not the whole world in October.',
            'NEW — You can finally see what you are playing for. The season screen now shows every event with its real status and what it actually requires: "5th of 10 — inside the cut", "Berth banked for 2029", "Club qualified — you are 16, minimum 17". It replaces two fixed chips, one of which claimed Worlds was decided by championship points — which has never been the rule. There is also a live banner while you are actually in a tournament, naming the round, the opponent and when the final is.',
            'NEW — Burnout. Let your morale sit on the floor for long enough and it stops being a number you can ignore: you get warned, then you get benched, and if nothing changes you get moved on. The bench is a genuine reset rather than a punishment spiral — the counter freezes while you are out and you come back above the line — but it costs you games, form and a season.',
            'NEW — Contract terminations. Your club reviews you, and a run of bad reviews is a strike. Three strikes and the deal is torn up early. Performing is now a condition of employment rather than something that only affects your next offer.',
            'CHANGED — morale and health actually do something. Both now move your in-game decisions, built as penalties that fade rather than bonuses that stack, so playing on a bad week is a real cost while playing on a good one is simply normal. Six new weekly activities exist to manage them, grouped so it is clear which ones buy morale, which buy health and which buy rest.',
            'CHANGED — solo queue starts at Gold, not Iron. A Pre-Competitive career opens in Gold IV and an Academy Debut in Platinum I. Climbing out of Iron was a dozen weeks of nothing at the start of every career.',
            'NEW — a career now starts where a real one does. Your first team is an amateur side with no consequences for leaving the moment a real contract appears; academy sides will not look at you until your rating justifies it; and outside your home region you cannot be signed above tier 3 as a first team. Once you have played a first team anywhere, the world opens up.',
            'NEW — age gates. You cannot hold a main-league seat until you are 16, and you cannot play a major international until you are 17 — the same rule the real leagues run. If your club qualifies and you are too young, you are told so plainly rather than quietly left out. Existing saves are grandfathered: nobody already holding a seat loses it.',
            'NEW — home region clubs chase you harder. Sides from the scene that raised you scout you more often and value you more highly, and moving abroad costs you standing at home that coming back partly refunds. Staying is now a real option rather than the absence of a better one.',
            'FIXED — second and third signature champions. Designating more than one signature champion did not work at all. You can now add and drop them properly, and see at a glance which of your champions are eligible.',
            'NEW — Trophy cabinet. Your honours are grouped into real shelves — Worlds, International, Domestic and Individual — with six regional titles shown as one plate with a count and six dated wins rather than six identical chips.',
            'NEW MINIGAME — Combo Execution replaces the Last Hit drill for Mechanics. Targets appear around the field inside a ring that shrinks onto them, and you hit each one at the instant the ring lands: perfect, great, good or miss, on a ±30ms window, with a combo a miss resets. The old drill trained a single axis and could be played by staring at one pixel. Mechanics is hands — aim and rhythm together — so the drill is now both. Playable by clicking the target or with Space.',
            'EXPANDED — the Game Knowledge quiz went from 65 questions to 108, and three of the old ones were simply wrong. Everything was re-checked against the current patch rather than written from memory: the first minion wave spawns at 0:30 (not 1:05), buff camps at 0:55 (not 1:30), and waves speed up to every 25 seconds at 14:00. The new questions cover what the game actually looks like now — Voidgrubs, Atakhan, Faelights, Role Quests and the removal of Feats of Strength.',
            'FIXED — your club can no longer be seeded out of an international it qualified for, and an unfinished summer bracket can no longer swallow the championship points that decide who goes to Worlds.',
        ],
    },
    {
        ver: 'Beta 1.6.9.2',
        title: 'Brazil — CBLOL Cards & a Sixth Career Region',
        summary: '678 new Brazilian cards covering thirteen seasons of CBLOL, Brazil added as a playable Ultimate Career region with ten real clubs, and the update log moved out to the main menu where you can read it without loading a save.',
        details: [
            'NEW CARDS — 678 of them, covering every Split 2 the Brazilian league has ever played: CBLOL 2014 through 2024, the 2025 season it spent merged into the LTA as "LTA South", and CBLOL 2026. That is 112 team rosters across 34 organisations, from the KaBuM! side that beat Alliance at Worlds 2014 to the LOUD team that reached the 2022 group stage. Every player is rated to how that specific split actually went — the final table sets a team\'s level and individual performance separates the players inside it.',
            'ONE REGION, NOT TWO — 2025 was branded LTA South for a single season before the CBLOL name came back in 2026. It is the same league, so all thirteen seasons sit under one 🇧🇷 CBLOL filter in the Archive instead of being split across two tabs you would have to check separately.',
            'A MINOR REGION THAT READS LIKE ONE — Brazilian cards top out at 90 and exactly one reaches it: Tinowns, on the 2022 LOUD side. The region\'s average sits below every major league, and the early years are rated as the semi-professional scene they actually were, so a 2014 card and a 2024 card are not pretending to be the same standard.',
            'NEW — Brazil in Ultimate Career: a sixth region on the "Which scene raised you?" screen, with ten main-league clubs (LOUD, Los Grandes, FURIA, Vivo Keyd Stars, RED Canids Kalunga, paiN Gaming, Fluxo W7M, Leviatán, KaBuM! and INTZ) and eight academy sides. Every club fields its real roster, pulled from the new cards.',
            'WHAT BRAZIL COSTS YOU — the joint-largest starting attribute bonus in the game and the loudest crowd in the world, against the worst wages anywhere and the weakest clubs in the mode. You will be a star at home; getting the rest of the world to notice you is the hard part.',
            'MOVED — the Update Log (this page) now lives on the main menu instead of being a tab inside Ultimate Roster, so you can read what changed without loading a save. The Home page\'s "Latest Updates" island still opens it and brings you straight back to your game.',
            'FIXED (Career) — contract offers no longer name a player from a completely unrelated club as the man you would be replacing. A sloppy name match meant Cloud9 could list LOUD\'s roster, Nongshim RedForce could list RED Canids\', and paiN Gaming could list GAM Esports\'.',
            'FIXED (Career) — your club can no longer be cut from an international tournament it had just qualified for. Winning your league and then being told you were "in the draw" while the whole event simulated without you was possible in any region and permanent in the weakest ones: a Brazilian or Asia-Pacific side never once reached MSI.',
            'FIXED (Career) — the "Played All Five Regions" milestone still counted to five when there are now six, so it was paying out to careers that had skipped one entirely. It counts every region now, whatever the number.',
        ],
    },
    {
        ver: 'Beta 1.6.8.1',
        title: 'Ultimate Career — The Legends Board',
        summary: 'A global leaderboard for Ultimate Career: publish your pro, browse everyone else\'s careers, and open a full dossier on any of them — their card, the five teammates they play with, and every season they\'ve ever played.',
        details: [
            'NEW — Legends board (Ultimate Career): a global leaderboard of other people\'s pros, sitting in a new "🌍 Legends" tab beside Profile. Anyone can browse it, signed in or not. Publish one career from any of your three save slots, and take it back down whenever you like.',
            'NEW — Career dossiers: click anybody on the board to read their whole career, not just their row. Their player card, all eight attributes against their ceiling, their genetic trait, their champion pool and how many games they have on each, every trophy and award, and their full season-by-season record with the club they played it for and where they finished.',
            'NEW — The Room: every dossier shows the five cards that career actually plays alongside — the club\'s starting roster, its coach, how the room is going right now, and every roster move the org has made since they arrived. It also appears on your OWN Profile, so you can finally see your teammates as cards.',
            'FIVE WAYS TO RANK — sort the board by Legacy, Peak OVR, Games, Wins, or Completed (retired careers first). Each is a real re-query of the whole board rather than a re-shuffle of the page you already have, so the top 50 is genuinely the top 50 for whichever column you picked. Filter the loaded rows by role, region or retirement.',
            'LEGACY IS EARNED, NOT BOUGHT — the board ranks on legacy you won on the pitch. Monuments from the Legacy Exchange are shown next to your score but never counted into your position, for the same reason the Hall of Legends has never been for sale: a renewable currency should not be able to buy the top of a leaderboard.',
            'PRIVACY — nothing is published until you press Publish, and only the career you choose. Condition (morale, energy, health), gold, contracts and pending offers never leave your device. One career per account is on the board at a time, and removing it deletes everything that was uploaded.',
            'FIXED (Profile) — clicking your own player card opens the card inspector again. A change made while building the board had quietly stopped it.',
            'FIXED (Profile) — a damaged save no longer invents a rating. If your role can\'t be read, the header honestly shows "Unknown" instead of confidently claiming a rating and a squad status it made up.',
            'FIXED — the board says what actually went wrong when it can\'t reach the server. Ad blockers and privacy extensions block the database this game uses, and the old message blamed the server instead of naming the real cause — which also silently affected cloud saves and the roster leaderboard.',
        ],
    },
    {
        ver: 'Beta 1.6.0',
        title: 'Main Menu, Summer Splits 2021–2023 & a Tighter Start',
        summary: '666 new cards filling the 2021–2023 gap, a brand-new main menu with gamemode select and a loading screen, and a much tighter starting economy.',
        details: [
            'NEW CARDS — 666 of them: complete LCK, LPL and LEC Summer Split rosters for 2021, 2022 and 2023 (main teams + head coaches, no academies). This closes the gap that ran from the 2020 Summer rosters all the way to 2024. Every player is rated to that season\'s real performance, so the era\'s defining runs land where they should — EDG\'s 2021 Worlds title, DAMWON KIA at their peak, DRX\'s 2022 Cinderella run, JDG\'s 2023 near-Golden-Road, and T1\'s 2023 world championship. Regions: LCK / LPL / LEC.',
            'NEW — Main Menu: a proper front door that opens before the game every time, with a new "UR" brand mark, a modernist wordmark, a login shortcut, and two gamemodes to pick from. Selecting one plays a loading screen with rotating gameplay tips. A "⌂ Menu" button in the header takes you back at any time.',
            'NEW — Ultimate Career (in development): play as the PLAYER, not the manager. Create a pro from nothing — handle, role, region and playstyle — grind out of the academy, beat your own teammates to the starting seat, and chase a Hall of Legends career. The menu entry is live; the mode itself is not playable yet.',
            'FIXED — the site no longer flashes a white page with loose footer text while loading. The dark theme and a small loading mark now paint on the very first frame, before the app bundle arrives.',
            'FOOTER — the "In collaboration with SISL" credit and the Riot Games disclaimer now appear at the bottom of every screen, including the main menu and the Ultimate Career page.',
            'HEADER — the top navigation no longer overlaps the team chip and account buttons on narrower desktop windows (anything under about 1600px wide).',
            'ECONOMY — starting Blue Essence lowered from 1,000 to 100. New managers still get the free Starter Pack, but a good squad now has to be earned through the Gaming Cafe rather than bought on the first click.',
            'FIXED — five 2026 BNK FEARX cards (Clear, Raptor, VicLa, Diable, Kellin) shared card IDs with five Flyquest cards, so owning one would silently turn it into the Flyquest player on reload. The BFX cards now have their own IDs and are collectable properly.',
            'GUIDE — the Card Coverage table now shows 2021–2023 as covered for all three major regions.',
        ],
    },
    {
        ver: 'Beta 1.5.1',
        title: 'Updates Hub, Global Search & Fixes',
        summary: 'A dedicated Updates page, a search-everything Archive tab, a critical season-split crash fix, and a randomised Golden Road final.',
        details: [
            'NEW — Updates page: a dedicated, in-depth changelog (the tab you\'re reading now). The Home "Latest Updates" island is now a short preview whose heading and rows link straight here.',
            'NEW — Home Game Guide island: a one-tap shortcut into the full guide, sitting next to the trimmed updates preview so the Home page stays compact instead of stretching down the screen.',
            'NEW — Archive Global Search: a "🔍 Global Search" tab that searches across EVERY card type at once (name, team, year, tier or region), plus a browsable overview of all card types showing your completion for each.',
            'FIXED (critical) — Season Splits no longer freeze on a blank page for veteran managers. At high split numbers (roughly split 25+, and guaranteed by split 50) the opponent generator could demand more BOSS teams than there were slots to place them and loop forever, locking up the whole site. Boss counts are now clamped to the available slots and the generator is guard-railed so it can never hang again.',
            'GOLDEN ROAD — the world final now scales to a random 115–130 total power instead of a flat cap, so the climax is sometimes a breather and sometimes a genuine wall. A ramp bug that quietly held the final below its intended ceiling was fixed at the same time.',
            'GUIDE — refreshed to document Global Search, the new Updates tab, and the randomised Golden Road final.',
        ],
    },
    {
        ver: 'Beta 1.4.0',
        title: 'Summer Splits 2018–2020',
        summary: '637 new Summer Split cards (2018–2020), redesigned EWC / Champion / Team of the Year cards, and a league-wide stat rebalance.',
        details: [
            'NEW CARDS — 637 of them: complete LCK, LPL and LEC Summer Split rosters for 2018, 2019 and 2020 (main teams + head coaches, no academies). Every player is rated to that split\'s real performance, so the best performers rank highest — Uzi & Rookie (2018), the DAMWON 2020 Worlds core, and the G2 / FPX super-teams of 2019 sit at the top, while off-years (e.g. SKT missing the 2018 playoffs) are reflected too. Region tags: LCK / LPL / LEC (2018 EU teams tagged LEC).',
            'CARD REDESIGNS — EWC cards became a brushed gold-and-emerald "Trophy Forge" frame; Champion cards an imperial purple-and-gold "coronation"; Team of the Year an all-star platinum chrome. Diamond cards now use dark text (no more mixups with coach cards) and the Grandmaster red is softer on the eyes.',
            'EWC 2026 (Dplus KIA) buffed — Smash and ShowMaker headline the upgrades, with the whole roster raised to match their Cinderella run.',
            'BENCH — the bench picker now shows every eligible card with role filters and sort-by-any-stat (rating or MEC/TMF/FRM/CMP/MAP/LDR).',
            'GOLDEN ROAD — the final Worlds stage is now capped at 120 total power, so a fully-built squad can realistically finish the gauntlet.',
            'BALANCE — a league-wide pass so every card\'s rating lines up with its stats: an elite 98–100 stat now only appears on elite-rated cards, and coach Mechanics are consistent across the board.',
        ],
    },
    {
        ver: 'Beta 1.3.4',
        title: 'Transfer Market',
        summary: 'The Trade tab is now a fully transparent Transfer Market — you always see exactly which player you\'re signing.',
        details: [
            'TRANSFER MARKET — the Trade tab now shows exactly which player you\'re signing (no more mystery). A randomised board of 6 real listings refreshes every 15 minutes; each can be signed once per rotation. Cost (spare cards + Blue Essence) scales with the player\'s tier, from Gold all the way up to Challenger and Legacy/Award cards.',
        ],
    },
    {
        ver: 'Beta 1.3.0',
        title: 'RBCs & EWC',
        summary: 'Roster Building Challenges, Esports World Cup champion cards, and a reworked Mystery Trade market.',
        details: [
            'NEW MODE — Roster Building Challenges (RBCs): a new tab between Academy and Season. Complete daily themed 5-player challenges by submitting cards from your Club — the cards are consumed and you earn 5 free packs to open in the Store. Five challenges (difficulty 1–5) with rewards scaling from Premium packs up to full EWC packs. Everything resets at midnight.',
            'NEW CARDS — Esports World Cup (EWC) champions: EWC 2024 (T1), EWC 2025 (Gen.G) and EWC 2026 (Dplus KIA). Each EWC card is a strictly upgraded edition of that player\'s base card, scaled to their run. New EWC card tier plus an EWC Store pack (4,000 BE).',
            'TRADE MARKET REWORKED — trades are finally worth doing. The new Mystery Trades consume your spare cards plus Blue Essence for ONE fully random player, guaranteed Master tier or higher, all the way up to Legacy & Award cards. Three tiers with escalating cost and better odds.',
            'UI — Friends moved up next to Ranking so the top nav is balanced; Home career stats reordered by prestige (Golden Road → Worlds → MSI → First Stand → Regional → Splits) with a unique colour each; team colour is now far more visible on the Home page panels.',
        ],
    },
    {
        ver: 'Beta 1.2.3',
        title: 'Fixes & Accessibility',
        summary: 'Transfer Network & Wealth fixes, a daily-login streak bonus, cloud-save reliability, and full accessibility support.',
        details: [
            'FIXED — the Transfer Network skill now actually boosts your sell prices (+5% per level). It was doing nothing before — check your Skills tab!',
            'Wealth Management now also boosts Blue Essence from card sells and daily logins, not just tournament and quest rewards.',
            'NEW — Daily Login streak bonus: every consecutive day you claim grants escalating bonus BE, up to +1,500 at a 30-day streak.',
            'FIXED — Cloud saves no longer drop your Prestige, daily streak, bench, or Showcase, and now validate your roster on load just like local saves.',
            'Accessibility & mobile: full keyboard navigation with focus-trapped menus, visible focus outlines, reduced-motion support, and pinch-to-zoom is re-enabled on phones.',
            'Under the hood: unified match chemistry logic for more consistent balance, plus dead-code cleanup.',
        ],
    },
    {
        ver: 'Beta 1.2.2',
        title: 'Foil & Signature Polish',
        summary: 'Brighter holographic foil, a prestige glow-up for signature cards, and an MSI 2026 (HLE) rebalance.',
        details: [
            '✨ Holographic cards are far easier to spot — the rainbow foil is now brighter and more opaque, and a soft pale wash lifts the base tier colour so the shimmer reads clearly on every card.',
            'Signature cards got a prestige glow-up — a bright white light-sweep glides across the card face and the border shimmers white → gold.',
            'MSI 2026 (HLE) rebalanced — the MSI-champion versions of Zeus, Kanavi, Zeka, Gumayusi and Delight now beat their base 2026 cards on every stat, scaled up to their title-winning run.',
        ],
    },
    {
        ver: 'Beta 1.2.1',
        title: 'Friend List',
        summary: 'The Friends tab arrives — add managers by name, challenge their squads, and sync friendships across devices.',
        details: [
            'FRIEND LIST — a brand-new Friends tab! Search for other managers by their exact display name and send them a friend request.',
            'Accept or decline incoming requests, cancel outgoing ones, and remove friends whenever you like — a header badge shows how many requests are waiting.',
            'View a friend\'s team and synced squad, or challenge them straight to a Tournament match against their saved five.',
            'Friendships sync live across your devices (sign-in required).',
        ],
    },
    {
        ver: 'Beta 1.2',
        title: 'Academy & Auto-Farming',
        summary: 'An Academy auto-farming team, Club bulk-sell tools, and MSI 2026 champions (HLE).',
        details: [
            'ACADEMY TEAM — a new tab next to Squad, unlocked after you win Worlds. Field a second five (separate from your main squad) and send them to auto-farm once every hour for Blue Essence and XP that scale with the team\'s rating. The roster locks while a run is training; collect your rewards when the hour is up. Assigned players are protected from selling.',
            'Club Vault — Quick Sell by tier: one click bulk-sells every card of a chosen tier (Bronze through Challenger) after a confirmation. Locked, favourited, squad, and academy cards are always kept.',
            'Club Vault — Sell Duplicates: instantly sell every extra copy of a player while keeping your best one.',
            'Challenger cards can no longer be crafted — the Upgrade Lab now tops out at Grandmaster, and the Trade Market\'s Diamond/Master/Grandmaster → Challenger recipes were removed. Challenger cards are still obtainable from packs.',
            'MSI 2026 — Hanwha Life Esports crowned champions, beating Bilibili Gaming 3-2 with Zeus as Finals MVP. Their winning roster is now in the game as MSI cards: Zeus, Kanavi, Zeka, Gumayusi, Delight + Mowgli (coach). Cards 9224–9229.',
            'Global Leaderboard is now public — browse the rankings without signing in. Sign in to add your own team to the board.',
            'Softer Bronze card art — the harsh dark-brown bronze tier now uses a warmer, lighter finish.',
            'Tabs: "Board" renamed to "Ranking"; the Rewards tab moved up next to Quests.',
        ],
    },
    {
        ver: 'Beta 1.1.6',
        title: 'Public Build',
        summary: 'MSI 2015 EDG cards (the inaugural champions) and a full Card Coverage table added to the Guide.',
        details: [
            'MSI 2015 EDG cards added — 6 new cards from the INAUGURAL MSI champion (ClearLove, PawN, Deft, Meiko, Koro1, Aaron). Stats based on real tournament data: ClearLove had 10.0 KDA (best in tournament), Finals MVP.',
            '2015 is now the earliest year with MSI coverage — 2015 was the first ever MSI (no earlier tournaments exist).',
            'Guide: Card Coverage table updated to show MSI 2015–2025 (no 2020), MSI History section updated with 2015 entry.',
            'Leaderboard power now correctly includes Conditioning skill bonus (fixes Squad vs Leaderboard mismatch).',
            'Card Coverage by Region & Year table added to Guide — shows which years each region is in the game, and all special card types with packs, years, and teams.',
        ],
    },
    {
        ver: 'Beta 1.1.5',
        title: 'Real-Data MSI Cards',
        summary: '12 MSI champion cards built from real tournament data, Battle Pass Claim All, anti-cheat, and Infinity Tower scaling.',
        details: [
            'Battle Pass: Claim All button — collect every unlocked reward in one click.',
            '12 new MSI champion cards based on real tournament data: SKT T1 2017 MSI (Huni/Peanut/Faker/Bang/Wolf/kkOma) and SKT T1 2016 MSI (Duke/Blank/Faker/Bang/Wolf/kkOma) — stats derived from actual KDA, damage share, and kill participation.',
            'MSI 2026 Event extended to July 12 — boosted drop rates, 3,500 BE pack price.',
            'New promo code: MSI2026 — free Signature MSI card (account panel).',
            'Guide: MSI History section with year-by-year champion rosters, real stats, and card IDs.',
            'Salary Cap flex picks: any card can fill any role at 25% salary discount + −10% stat debuff.',
            'Wealth Management: +X% BE badge in header, bonus shown in all reward toasts.',
            'Anti-cheat: save integrity hash, card stat validation on load, Firebase leaderboard security rules.',
            'Unique team names auto-generated for new players (no more duplicate "My Team" on leaderboard).',
            'Infinity Tower: starts at Gold tier, scales infinitely past floor 20 with no cap.',
            'Leaderboard now shows Blue Essence as a sortable column.',
        ],
    },
    {
        ver: 'Beta 1.1.2',
        title: 'Awards, Salary Cap & Prestige',
        summary: 'League Award cards (POTY/TOTY/ROTY), Salary Cap Mode, the Rival Challenge, and the Prestige system.',
        details: [
            'League Awards 2024 & 2025 cards: POTY (Faker, Chovy), TOTY (T1 full lineup both years), ROTY (Massu, HongQ) — 14 new ultra-rare cards.',
            'Awards Vault pack: 12,000 BE · 0.25% POTY · 1% TOTY · 3% ROTY — rarest pack in the game.',
            'Salary Cap Mode: Build a 50,000 CAP squad from your club. Cards priced by rating. Beat elite opponents for 8,000 BE.',
            'Rival Challenge: Fight another leaderboard player\'s saved squad. 3-match series, 3,000 BE reward.',
            'Prestige System: Reach Manager Lv 100 to Prestige. Resets XP/Skills, keeps all cards/BE/trophies. ⭐ badge in header.',
            'Career Milestone Cards: Earn special cards for achievements (First Worlds, Golden Road, Tower 100, etc.) Shown on Home page.',
            'Coming Soon updated: Friend List, Player Form System.',
        ],
    },
    {
        ver: 'Beta 1.1.1.2',
        title: 'Quests & Draft Fixes',
        summary: '55 milestone quests, 25 achievements, and a batch of Draft Mode fixes.',
        details: [
            '55 milestone quests (was 39), 10 repeatable contracts (was 7), 25 achievements (was 17).',
            'New Draft Mode quests: Win/Play Draft milestones + repeatable contract.',
            'New economy quests: Perform 10/50 Upgrades.',
            'Higher-tier competitive goals: Win 10 First Stands, Win 5 MSIs, Win 5 Worlds, Win 100 Cafes.',
            'New achievements: 98+ Squad Avg, Manager Lv 100, Tower Floor 200, Own 1000 Cards, Win 10/50 Drafts.',
            'Draft Mode: cards now sort by natural role when picking for a position.',
            'Draft Mode: card clicks work properly for banning and picking (no more inspect popup).',
            'Draft Mode: squad cards displayed on sides during match phase.',
            'MSI event pity counter now updates live after each pack open.',
            'ON (BLG) 2026 FirstStand card buffed to 97 to match base card.',
        ],
    },
    {
        ver: 'Beta 1.1.0',
        title: 'Draft Mode',
        summary: 'Draft Mode, the MSI 2026 limited event, the Wealth Management skill, and a Conditioning fix.',
        details: [
            'DRAFT MODE — New gamemode! 15 random cards, 5 bans each side, build a squad, best of 5. Off-role flex penalty (-10 stats), legacy cards are wildcards.',
            'MSI 2026 LIMITED EVENT — 24hr global event with boosted MSI pack drop rates + guaranteed MSI card pity at 70 pulls.',
            'Wealth Management skill: +10% bonus BE from all rewards per level (max 5).',
            'Conditioning skill now works: +1 total power per level across all modes.',
            'Dynamic milestones on Home page, Legacy card tracker, Career stats expanded.',
            'Card Showcase moved to Club with drag-and-drop reordering.',
            'Archive completion uses full team size, Coming Soon gamemodes in Play tab.',
        ],
    },
    {
        ver: 'Beta 1.0.9.2',
        title: 'Showcase & Combat Overhaul',
        summary: 'Card Showcase, split squad-lock with bench swaps, and a combat UI overhaul.',
        details: [
            'Card Showcase with drag-and-drop in Club Vault.',
            'Squad locks during active season splits — bench swaps only.',
            'Bench Management skill (max 3) for mid-split player swaps.',
            'Combat UI overhaul: Power bar, Stat vs Net split, full log breakdown.',
            'Upgrade Lab notification badges per tier and role.',
            'Battle Pass auto-levels, Leaderboard autosync, Redeem codes.',
            'Player ratings updated for 2025-2026 based on real performance data.',
        ],
    },
    {
        ver: 'Beta 1.0.9.1',
        title: 'Quest Badges & Persistent Cooldowns',
        summary: 'Quest notification badges, stacking contracts, persistent split cooldowns, and an expanded meta.',
        details: [
            'Trades lock instantly after completing — no repeat claims.',
            'Quest sub-tabs show notification badges for claimable rewards.',
            'Repeatable contracts stack — excess progress carries over.',
            'Archive claim buttons moved inside sub-tabs.',
            'Battle Pass XP earned from all gameplay modes.',
            'Tactical Mastery bonus visibly applied in combat.',
            'Season split cooldown timer persists across tabs and page reloads.',
            'Header cooldown timer chip — click to jump to Season tab.',
            'Expanded meta: 5 buffed, 12 slumping teams per phase.',
            'CPU team generation enforces rating caps.',
            'Gaming Cafe capped at 78 power, Regional Trophy at 93.',
            '39 milestones, 7 contracts, 17 achievements.',
            'Leaderboard shows other players\' squads and showcase.',
            'Archive rewards: per-card discovery + team completion.',
            'Notification badges on Archive, Quests, Skills, Rewards tabs.',
        ],
    },
    {
        ver: 'Beta 1.0.7',
        title: 'Era Synergy, Tower & Battle Pass',
        summary: 'Era synergy, Signature/Holographic cards, Infinity Tower, Golden Road, and the 100-tier Battle Pass.',
        details: [
            'Era synergy replaces year synergy (6 eras grouping years into 3-year blocks).',
            'Signature cards +2 all stats/rating, Holographic +1, stackable, can exceed 99.',
            'Pack preview shows exact drop rates with scouting bonus.',
            '3-column combat layout with 2×3 card grids.',
            'Infinity Tower: endless floors, roguelike upgrades, persistent runs.',
            'Golden Road: 4-stage tournament gauntlet with 30-min cooldown.',
            'Trade Market with 15-min rotation and skill-based scaling.',
            'Daily Login (28-day cycle) and 100-tier Battle Pass.',
            'Manager XP system with central grantXP function across all modes.',
        ],
    },
];

// The newest N updates, for the Home page preview island.
export function recentUpdates(n = 3) {
    return UPDATES.slice(0, n);
}
